"""quitar nombre calle y numero espacio

Revision ID: 078837f6116e
Revises: abbc4fd91969
Create Date: 2026-05-21 22:00:37.340349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '078837f6116e'
down_revision: Union[str, Sequence[str], None] = 'abbc4fd91969'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calles', 'nombre')
    op.drop_column('espacios', 'numero')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('espacios', sa.Column('numero', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('calles', sa.Column('nombre', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
